const arts = {
    Scroom: {
      dps: 1,
      mult: 1,
      nivel: 1,
      fusion: 10,
      update: 'MetaScroom',
      nombre: 'seta ⭐',
      key: 'Scroom',
      image:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fterrados.es%2Fwp-content%2Fuploads%2F2013%2F12%2Fboletus_edulis.png&f=1&nofb=1',
    },
    MetaScroom: {
      dps: 11,
      mult: 1,
      nivel: 1,
      fusion: 10,
      update: 'setas',
      nombre: 'seta metalica ⭐',
      key: 'MetaScroom',
      image:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fvignette.wikia.nocookie.net%2Frogue-lineage%2Fimages%2Ff%2Ffd%2FCapture.JPG%2Frevision%2Flatest%3Fcb%3D20190720224034&f=1&nofb=1',
    },
    Sus: {
      dps: 2,
      mult: 1,
      fusion: 10,
      update: 'Sus2',
      nivel: 1,
      nombre: 'Cosa sospechosa ⭐',
      key: 'Sus',
      image: 'https://acegif.com/wp-content/uploads/2020/11/am0ngsusxh-36.gif',
    },
    Sus2: {
      dps: 22,
      mult: 1,
      fusion: 20,
      update: '',
      nivel: 1,
      nombre: 'SUS ⭐⭐',
      key: 'Sus2',
      image: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia1.tenor.com%2Fimages%2Fa736455eede608798c4215193087ad73%2Ftenor.gif%3Fitemid%3D18888018&f=1&nofb=1',
    },
    Furias: {
      costo: 1000,
      dps: 20,
      mult: 1,
      nivel: 1,
      update: 'goku2',
      fusion: 10,
      image:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fvignette.wikia.nocookie.net%2Frogue-lineage%2Fimages%2Fe%2Fed%2FHaselden.png%2Frevision%2Flatest%3Fcb%3D20191107065431&f=1&nofb=1',
      nombre: 'chupada a furias ⭐⭐',
      key: 'Furias',
    },
    Darius: {
      dps: 50,
      update: 'Darius2',
      nivel: 1,
      fusion: 5,
      mult: 1,
      nombre: 'abuela darius en top ⭐⭐⭐⭐',
      image:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.models-resource.com%2Fresources%2Fbig_icons%2F7%2F6694.png&f=1&nofb=1',
      key: 'Darius',
    },
    Darius2: {
      update: '',
      dps: 500,
      fusion: 10,
      nivel: 1,
      mult: 1,
      nombre:
        'abuela darius en top con fantasmal e ignite (tu que miedo) ⭐⭐⭐⭐⭐⭐',
      image: 'https://c.tenor.com/JlqocrEEmlMAAAAd/darius-league-of-legends.gif',
      key: 'Darius2',
    },
    Payaso: {
      update: 'payaso2',
      dps: 100,
      fusion: 10,
      nivel: 1,
      mult: 1,
      nombre: 'copia exacta de ti mismo ⭐⭐⭐',
      image: 'https://dbdzm869oupei.cloudfront.net/img/sticker/preview/495.png',
      key: 'Payaso',
    },
    Teemo: {
      update: 'cancer',
      dps: 90,
      nivel: 1,
      fusion: 10,
      mult: 1,
      nombre: 'rata qla conche su mare webon ⭐⭐⭐',
      image:
        'https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Forig06.deviantart.net%2Fcc84%2Ff%2F2012%2F218%2Fb%2Ff%2Fteemo_render__default_skin__by_aurablade-d59zqef.png&f=1&nofb=1',
      key: 'Teemo',
    },
    Yummi: {
      update: '',
      dps: 50,
      fusion: 10,
      nivel: 1,
      mult: 1,
      nombre: 'main top ⭐⭐⭐⭐',
      image:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fvignette.wikia.nocookie.net%2Fleagueoflegends%2Fimages%2Fd%2Fd5%2FYuumi_Render.png%2Frevision%2Flatest%3Fcb%3D20190502165317&f=1&nofb=1',
      key: 'Yummi',
    },
    Chad: {
      update: 'GigaChad',
      dps: 200,
      fusion: 10,
      nivel: 1,
      mult: 1,
      nombre: 'representacion de ti en tus pensamientos ⭐⭐⭐⭐⭐',
      image: 'https://i.kym-cdn.com/photos/images/facebook/002/220/732/0b1.png',
      key: 'Chad',
    },
    GigaChad: {
      update: '',
      dps: 2200,
      fusion: 10,
      nivel: 1,
      mult: 1,
      nombre: 'ojala fueras tu así ⭐⭐⭐⭐⭐⭐',
      image: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.pinimg.com%2F736x%2F3a%2F1c%2Fd9%2F3a1cd955b2e0f3923192b64154156089.jpg&f=1&nofb=1',
      key: 'GigaChad',
    },
    Furry: {
      update: 'genshin2',
      dps: 100,
      nivel: 1,
      fusion: 9,
      mult: 1,
      nombre: 'supuesta jugadora de genshin impact ⭐⭐⭐⭐⭐',
      image: 'https://i.redd.it/6g02zowzahx71.jpg',
      key: 'Furry',
    },
    Energuia: {
      update: '',
      dps: 600,
      fusion: 10,
      nivel: 1,
      mult: 1,
      nombre: 'neko kawaii ⭐⭐⭐⭐⭐⭐',
      image: 'img/neko.png',
      key: 'Energuia',
    },
    discord: {
      update: 'discord_senior',
      dps: 150,
      nivel: 1,
      fusion: 10,
      mult: 1,
      nombre: 'moderadora de discord uwu ⭐⭐⭐⭐⭐',
      image:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.ytimg.com%2Fvi%2F4eHoLq_2vOA%2Fmaxresdefault.jpg&f=1&nofb=1',
      key: 'discord',
    },
    discord_senior: {
        update: '',
        dps: 1600,
        nivel: 1,
        fusion: 10,
        mult: 1,
        nombre: 'Moderador de discord senior ⭐⭐⭐⭐⭐⭐',
        image:
          'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.ytimg.com%2Fvi%2F4eHoLq_2vOA%2Fmaxresdefault.jpg&f=1&nofb=1',
        key: 'discord_senior',
      },
    goku2: {
      update: '',
      dps: 250,
      nivel: 1,
      fusion: 10,
      mult: 1,
      nombre: 'golpeador de mujeres ⭐⭐⭐⭐⭐',
      image:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.pngkit.com%2Fpng%2Ffull%2F393-3930198_dragon-ball-clipart-super-saiyan-goku-ssj-db.png&f=1&nofb=1',
      key: 'goku2',
    },
    n: {
      update: '',
      dps: -100,
      nivel: 1,
      fusion: 10,
      mult: 1,
      nombre: 'N̵̪͍͓̞̠͔̿̓̆͗̍̇̍͒͛̀̂̉̈́ͅÍ̵̱͙̊̃̏͐̉͊͋̇̚̚͝͝͝Ǵ̶̰̖̯͖͗͑͑̏̔̾̕̚G̴̨̛̙̘̜̯͓̣̰̘̲͐̃̊̌̃A̵̼͔͔͈̺͋́̓̏̎́̀̆͌̕',
      image:
        'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.redd.it%2Fkz29pseqp7d41.jpg&f=1&nofb=1',
      key: 'n',
    },
    nft: {
      update: '',
      dps: 999999,
      nivel: 1,
      fusion: 10,
      mult: 1,
      nombre: 'Captura de pantalla',
      image:
        'https://libres.io/wp-content/uploads/2021/12/download-3.png',
      key: 'nft',
    },
    genshin2: {
      update: '',
      dps: 1000,
      nivel: 1,
      fusion: 10,
      mult: 1,
      nombre: 'Diabetes grado 2 ⭐⭐⭐⭐⭐⭐⭐⭐⭐',
      image:
        'https://imagenes.elpais.com/resizer/fjYH-qJ1BjwgKHoEVG2z394qNe4=/1960x1470/cloudfront-eu-central-1.images.arcpublishing.com/prisa/N37WKWJULVG4XDD2IP2WZVCECA.jpg',
      key: 'genshin2',
    },
    cancer: {
      update: '',
      dps: 1000,
      nivel: 1,
      fusion: 10,
      mult: 1,
      nombre: 'Literalmente Cancer ⭐⭐⭐⭐⭐',
      image:
        'https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fenacademic.com%2Fpictures%2Fenwiki%2F83%2FSymptoms_of_cancer_metastasis.png&f=1&nofb=1',
      key: 'cancer',
    },
    payaso2: {
        update: '',
        dps: 1100,
        nivel: 1,
        fusion: 10,
        mult: 1,
        nombre: 'POV eres el payaso ⭐⭐⭐⭐⭐',
        image:
          'https://i.pinimg.com/474x/9c/01/84/9c0184a25fd73c0a31f984a821a8cba4--the-circus-circus-theme.jpg',
        key: 'payaso2',
      },
      setas: {
        update: '',
        dps: 250,
        nivel: 1,
        fusion: 10,
        mult: 1,
        nombre: 'Setas de las buenas ⭐⭐⭐',
        image:
          'https://i.pinimg.com/474x/9c/01/84/9c0184a25fd73c0a31f984a821a8cba4--the-circus-circus-theme.jpg',
        key: 'setas',
      },

  }
  